from __future__ import annotations

import json
import sqlite3
import threading
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ASSET_KINDS = {"character", "motion", "animation"}
ASSET_STATUSES = {"pending", "queued", "running", "ready", "failed", "cancelled"}
ASSET_JOB_KINDS = {"rig", "motion", "retarget"}
ASSET_FILE_KINDS = {
    "character": {"source_glb", "rigged_glb", "topology_report", "mapping"},
    "motion": {"source_mp4", "motion_npz", "manifest", "preview_mp4", "preview_glb"},
    "animation": {"animated_glb", "retarget_report", "qa_report"},
}
ASSET_MIME_TYPES = {
    "source_glb": "model/gltf-binary",
    "rigged_glb": "model/gltf-binary",
    "animated_glb": "model/gltf-binary",
    "source_mp4": "video/mp4",
    "preview_mp4": "video/mp4",
    "preview_glb": "model/gltf-binary",
    "motion_npz": "application/octet-stream",
    "topology_report": "application/json",
    "mapping": "application/json",
    "manifest": "application/json",
    "retarget_report": "application/json",
    "qa_report": "application/json",
}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


@dataclass(frozen=True)
class Asset:
    id: str
    kind: str
    name: str
    status: str
    root_dir: Path
    source_sha256: str | None
    cache_key: str | None
    source_character_id: str | None
    source_motion_id: str | None
    render_keyframes: bool
    latest_job_id: str | None
    created_at: str
    updated_at: str
    error: str | None = None


@dataclass(frozen=True)
class AssetFile:
    id: str
    asset_id: str
    file_kind: str
    path: Path
    size_bytes: int
    sha256: str
    mime_type: str
    created_at: str


@dataclass(frozen=True)
class AssetJob:
    id: str
    job_type: str
    status: str
    asset_id: str
    character_id: str | None
    motion_id: str | None
    params_json: str
    work_dir: Path
    created_at: str
    updated_at: str
    started_at: str | None = None
    finished_at: str | None = None
    error: str | None = None

    @property
    def params(self) -> dict[str, Any]:
        try:
            value = json.loads(self.params_json)
        except json.JSONDecodeError:
            return {}
        return value if isinstance(value, dict) else {}


# The storage uses one normalized table with a constrained kind column. These
# aliases keep the domain model explicit for callers without duplicating the
# same columns across Character, Motion, and Animation tables.
Character = Asset
Motion = Asset
Animation = Asset


class AssetDatabase:
    """SQLite persistence for typed assets and their stage jobs.

    Paths are generated by the backend and stored as absolute controlled paths.
    API callers can only select a whitelisted file_kind; they never provide a
    filesystem path.
    """

    def __init__(self, path: Path, storage_root: Path) -> None:
        self.path = path
        self.storage_root = storage_root.resolve()
        self._lock = threading.RLock()

    def _connect(self) -> sqlite3.Connection:
        connection = sqlite3.connect(self.path, timeout=30, check_same_thread=False)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA journal_mode=WAL")
        return connection

    def initialize(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self._lock, self._connect() as connection:
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS assets (
                    id TEXT PRIMARY KEY,
                    kind TEXT NOT NULL,
                    name TEXT NOT NULL,
                    status TEXT NOT NULL,
                    root_dir TEXT NOT NULL,
                    source_sha256 TEXT,
                    cache_key TEXT,
                    source_character_id TEXT,
                    source_motion_id TEXT,
                    render_keyframes INTEGER NOT NULL DEFAULT 0,
                    latest_job_id TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    error TEXT,
                    UNIQUE(kind, cache_key)
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS asset_files (
                    id TEXT PRIMARY KEY,
                    asset_id TEXT NOT NULL,
                    file_kind TEXT NOT NULL,
                    path TEXT NOT NULL,
                    size_bytes INTEGER NOT NULL,
                    sha256 TEXT NOT NULL,
                    mime_type TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    UNIQUE(asset_id, file_kind)
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS asset_jobs (
                    id TEXT PRIMARY KEY,
                    job_type TEXT NOT NULL,
                    status TEXT NOT NULL,
                    asset_id TEXT NOT NULL,
                    character_id TEXT,
                    motion_id TEXT,
                    params_json TEXT NOT NULL,
                    work_dir TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    started_at TEXT,
                    finished_at TEXT,
                    error TEXT
                )
                """
            )
            connection.commit()

    def check(self) -> bool:
        with self._lock, self._connect() as connection:
            connection.execute("SELECT 1").fetchone()
        return True

    def _asset_from_row(self, row: sqlite3.Row) -> Asset:
        return Asset(
            id=str(row["id"]),
            kind=str(row["kind"]),
            name=str(row["name"]),
            status=str(row["status"]),
            root_dir=Path(row["root_dir"]),
            source_sha256=row["source_sha256"],
            cache_key=row["cache_key"],
            source_character_id=row["source_character_id"],
            source_motion_id=row["source_motion_id"],
            render_keyframes=bool(row["render_keyframes"]),
            latest_job_id=row["latest_job_id"],
            created_at=str(row["created_at"]),
            updated_at=str(row["updated_at"]),
            error=row["error"],
        )

    def _job_from_row(self, row: sqlite3.Row) -> AssetJob:
        return AssetJob(
            id=str(row["id"]),
            job_type=str(row["job_type"]),
            status=str(row["status"]),
            asset_id=str(row["asset_id"]),
            character_id=row["character_id"],
            motion_id=row["motion_id"],
            params_json=str(row["params_json"]),
            work_dir=Path(row["work_dir"]),
            created_at=str(row["created_at"]),
            updated_at=str(row["updated_at"]),
            started_at=row["started_at"],
            finished_at=row["finished_at"],
            error=row["error"],
        )

    def create_asset(
        self,
        *,
        asset_id: str | None = None,
        kind: str,
        name: str,
        root_dir: Path,
        source_sha256: str | None,
        cache_key: str,
        source_character_id: str | None = None,
        source_motion_id: str | None = None,
        render_keyframes: bool = False,
        status: str = "pending",
    ) -> Asset:
        if kind not in ASSET_KINDS or status not in ASSET_STATUSES:
            raise ValueError("unsupported asset kind or status")
        resolved_root = root_dir.resolve()
        try:
            resolved_root.relative_to(self.storage_root)
        except ValueError as exc:
            raise ValueError("asset root escapes storage root") from exc
        now = utc_now()
        asset = Asset(
            id=asset_id or str(uuid.uuid4()),
            kind=kind,
            name=name,
            status=status,
            root_dir=resolved_root,
            source_sha256=source_sha256,
            cache_key=cache_key,
            source_character_id=source_character_id,
            source_motion_id=source_motion_id,
            render_keyframes=render_keyframes,
            latest_job_id=None,
            created_at=now,
            updated_at=now,
        )
        with self._lock, self._connect() as connection:
            connection.execute(
                """
                INSERT INTO assets (
                    id, kind, name, status, root_dir, source_sha256, cache_key,
                    source_character_id, source_motion_id, render_keyframes,
                    latest_job_id, created_at, updated_at, error
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    asset.id,
                    asset.kind,
                    asset.name,
                    asset.status,
                    str(asset.root_dir),
                    asset.source_sha256,
                    asset.cache_key,
                    asset.source_character_id,
                    asset.source_motion_id,
                    int(asset.render_keyframes),
                    None,
                    asset.created_at,
                    asset.updated_at,
                    None,
                ),
            )
            connection.commit()
        return asset

    def get_asset(self, asset_id: str) -> Asset | None:
        with self._lock, self._connect() as connection:
            row = connection.execute("SELECT * FROM assets WHERE id = ?", (asset_id,)).fetchone()
        return self._asset_from_row(row) if row else None

    def list_assets(self, kind: str) -> list[Asset]:
        with self._lock, self._connect() as connection:
            rows = connection.execute(
                "SELECT * FROM assets WHERE kind = ? ORDER BY created_at DESC", (kind,)
            ).fetchall()
        return [self._asset_from_row(row) for row in rows]

    def find_ready_by_cache(self, kind: str, cache_key: str) -> Asset | None:
        asset = self.find_by_cache(kind, cache_key)
        return asset if asset is not None and asset.status == "ready" else None

    def find_by_cache(self, kind: str, cache_key: str) -> Asset | None:
        with self._lock, self._connect() as connection:
            row = connection.execute(
                """
                SELECT * FROM assets
                WHERE kind = ? AND cache_key = ?
                ORDER BY updated_at DESC LIMIT 1
                """,
                (kind, cache_key),
            ).fetchone()
        return self._asset_from_row(row) if row else None

    def delete_asset(self, asset_id: str) -> None:
        """Remove a partially-created database record during local rollback."""
        with self._lock, self._connect() as connection:
            connection.execute("DELETE FROM asset_jobs WHERE asset_id = ?", (asset_id,))
            connection.execute("DELETE FROM asset_files WHERE asset_id = ?", (asset_id,))
            connection.execute("DELETE FROM assets WHERE id = ?", (asset_id,))
            connection.commit()

    def set_asset_status(self, asset_id: str, status: str, error: str | None = None) -> None:
        if status not in ASSET_STATUSES:
            raise ValueError(f"unsupported asset status: {status}")
        with self._lock, self._connect() as connection:
            connection.execute(
                "UPDATE assets SET status = ?, error = ?, updated_at = ? WHERE id = ?",
                (status, error, utc_now(), asset_id),
            )
            connection.commit()

    def add_file(
        self,
        *,
        asset_id: str,
        file_kind: str,
        path: Path,
        size_bytes: int,
        sha256: str,
        mime_type: str | None = None,
    ) -> AssetFile:
        asset = self.get_asset(asset_id)
        if asset is None or file_kind not in ASSET_FILE_KINDS.get(asset.kind, set()):
            raise ValueError("unsupported asset file kind")
        resolved = path.resolve()
        try:
            resolved.relative_to(self.storage_root)
        except ValueError as exc:
            raise ValueError("asset file path escapes storage root") from exc
        try:
            resolved.relative_to(asset.root_dir.resolve())
        except ValueError as exc:
            raise ValueError("asset file path escapes asset directory") from exc
        record = AssetFile(
            id=str(uuid.uuid4()),
            asset_id=asset_id,
            file_kind=file_kind,
            path=resolved,
            size_bytes=int(size_bytes),
            sha256=sha256,
            mime_type=mime_type or ASSET_MIME_TYPES.get(file_kind, "application/octet-stream"),
            created_at=utc_now(),
        )
        with self._lock, self._connect() as connection:
            connection.execute(
                """
                INSERT INTO asset_files (
                    id, asset_id, file_kind, path, size_bytes, sha256, mime_type, created_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(asset_id, file_kind) DO UPDATE SET
                    path = excluded.path,
                    size_bytes = excluded.size_bytes,
                    sha256 = excluded.sha256,
                    mime_type = excluded.mime_type,
                    created_at = excluded.created_at
                """,
                (
                    record.id,
                    record.asset_id,
                    record.file_kind,
                    str(record.path),
                    record.size_bytes,
                    record.sha256,
                    record.mime_type,
                    record.created_at,
                ),
            )
            connection.commit()
        return record

    def get_file(self, asset_id: str, file_kind: str) -> AssetFile | None:
        asset = self.get_asset(asset_id)
        if asset is None or file_kind not in ASSET_FILE_KINDS.get(asset.kind, set()):
            return None
        with self._lock, self._connect() as connection:
            row = connection.execute(
                "SELECT * FROM asset_files WHERE asset_id = ? AND file_kind = ?",
                (asset_id, file_kind),
            ).fetchone()
        if row is None:
            return None
        return AssetFile(
            id=str(row["id"]),
            asset_id=str(row["asset_id"]),
            file_kind=str(row["file_kind"]),
            path=Path(row["path"]),
            size_bytes=int(row["size_bytes"]),
            sha256=str(row["sha256"]),
            mime_type=str(row["mime_type"]),
            created_at=str(row["created_at"]),
        )

    def list_files(self, asset_id: str) -> list[AssetFile]:
        asset = self.get_asset(asset_id)
        if asset is None:
            return []
        with self._lock, self._connect() as connection:
            rows = connection.execute(
                "SELECT * FROM asset_files WHERE asset_id = ? ORDER BY file_kind", (asset_id,)
            ).fetchall()
        return [
            AssetFile(
                id=str(row["id"]),
                asset_id=str(row["asset_id"]),
                file_kind=str(row["file_kind"]),
                path=Path(row["path"]),
                size_bytes=int(row["size_bytes"]),
                sha256=str(row["sha256"]),
                mime_type=str(row["mime_type"]),
                created_at=str(row["created_at"]),
            )
            for row in rows
        ]

    def create_job(
        self,
        *,
        job_type: str,
        asset_id: str,
        work_dir: Path,
        character_id: str | None = None,
        motion_id: str | None = None,
        params: dict[str, Any] | None = None,
    ) -> AssetJob:
        if job_type not in ASSET_JOB_KINDS:
            raise ValueError("unsupported asset job type")
        if self.get_asset(asset_id) is None:
            raise ValueError("asset does not exist")
        resolved_work_dir = work_dir.resolve()
        try:
            resolved_work_dir.relative_to(self.storage_root)
        except ValueError as exc:
            raise ValueError("asset job work directory escapes storage root") from exc
        now = utc_now()
        job = AssetJob(
            id=str(uuid.uuid4()),
            job_type=job_type,
            status="queued",
            asset_id=asset_id,
            character_id=character_id,
            motion_id=motion_id,
            params_json=json.dumps(params or {}, sort_keys=True),
            work_dir=resolved_work_dir,
            created_at=now,
            updated_at=now,
        )
        with self._lock, self._connect() as connection:
            connection.execute(
                """
                INSERT INTO asset_jobs (
                    id, job_type, status, asset_id, character_id, motion_id,
                    params_json, work_dir, created_at, updated_at,
                    started_at, finished_at, error
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    job.id,
                    job.job_type,
                    job.status,
                    job.asset_id,
                    job.character_id,
                    job.motion_id,
                    job.params_json,
                    str(job.work_dir),
                    job.created_at,
                    job.updated_at,
                    None,
                    None,
                    None,
                ),
            )
            connection.execute(
                "UPDATE assets SET status = 'queued', error = NULL, latest_job_id = ?, updated_at = ? WHERE id = ?",
                (job.id, utc_now(), asset_id),
            )
            connection.commit()
        return job

    def get_job(self, job_id: str) -> AssetJob | None:
        with self._lock, self._connect() as connection:
            row = connection.execute("SELECT * FROM asset_jobs WHERE id = ?", (job_id,)).fetchone()
        return self._job_from_row(row) if row else None

    def list_jobs(self) -> list[AssetJob]:
        with self._lock, self._connect() as connection:
            rows = connection.execute(
                "SELECT * FROM asset_jobs ORDER BY created_at DESC"
            ).fetchall()
        return [self._job_from_row(row) for row in rows]

    def queued_job_ids(self) -> list[str]:
        with self._lock, self._connect() as connection:
            rows = connection.execute(
                "SELECT id FROM asset_jobs WHERE status = 'queued' ORDER BY created_at"
            ).fetchall()
        return [str(row["id"]) for row in rows]

    def update_job_status(self, job_id: str, status: str, error: str | None = None) -> None:
        if status not in ASSET_STATUSES:
            raise ValueError(f"unsupported asset job status: {status}")
        now = utc_now()
        with self._lock, self._connect() as connection:
            row = connection.execute(
                "SELECT asset_id FROM asset_jobs WHERE id = ?", (job_id,)
            ).fetchone()
            if row is None:
                return
            connection.execute(
                """
                UPDATE asset_jobs
                SET status = ?, error = ?, updated_at = ?,
                    started_at = CASE
                        WHEN ? = 'running' AND started_at IS NULL THEN ?
                        ELSE started_at
                    END,
                    finished_at = CASE
                        WHEN ? IN ('ready', 'failed', 'cancelled') THEN COALESCE(finished_at, ?)
                        ELSE finished_at
                    END
                WHERE id = ?
                """,
                (status, error, now, status, now, status, now, job_id),
            )
            connection.execute(
                "UPDATE assets SET status = ?, error = ?, updated_at = ? WHERE id = ?",
                (status, error, now, row["asset_id"]),
            )
            connection.commit()

    def mark_running_interrupted(self) -> int:
        now = utc_now()
        with self._lock, self._connect() as connection:
            rows = connection.execute(
                "SELECT id, asset_id FROM asset_jobs WHERE status = 'running'"
            ).fetchall()
            connection.execute(
                """
                UPDATE asset_jobs
                SET status = 'failed', error = 'interrupted by service restart',
                    updated_at = ?, finished_at = COALESCE(finished_at, ?)
                WHERE status = 'running'
                """,
                (now, now),
            )
            for row in rows:
                connection.execute(
                    "UPDATE assets SET status = 'failed', error = 'interrupted by service restart', updated_at = ? WHERE id = ?",
                    (now, row["asset_id"]),
                )
            connection.commit()
            return len(rows)

    def asset_dict(self, asset: Asset) -> dict[str, Any]:
        file_records = self.list_files(asset.id)
        files = [
            {
                "file_kind": item.file_kind,
                "filename": item.path.name,
                "size_bytes": item.size_bytes,
                "sha256": item.sha256,
                "mime_type": item.mime_type,
            }
            for item in file_records
        ]
        body: dict[str, Any] = {
            "id": asset.id,
            "kind": asset.kind,
            "name": asset.name,
            "status": asset.status,
            "source_character_id": asset.source_character_id,
            "source_motion_id": asset.source_motion_id,
            "source_sha256": asset.source_sha256,
            "latest_job_id": asset.latest_job_id,
            "created_at": asset.created_at,
            "updated_at": asset.updated_at,
            "render_keyframes": asset.render_keyframes,
            "error": asset.error,
            "files": files,
        }
        if asset.latest_job_id:
            job = self.get_job(asset.latest_job_id)
            if job is not None and asset.kind == "motion":
                body["camera_mode"] = job.params.get("camera_mode")
        if asset.kind == "motion":
            manifest = next((item for item in file_records if item.file_kind == "manifest"), None)
            if manifest is not None:
                try:
                    metadata = json.loads(manifest.path.read_text(encoding="utf-8"))
                except (OSError, json.JSONDecodeError):
                    metadata = {}
                if isinstance(metadata, dict):
                    for key in ("frames", "fps", "duration_seconds"):
                        value = metadata.get(key)
                        if isinstance(value, (int, float)) and not isinstance(value, bool):
                            body[key] = value
        return body

    def job_dict(self, job: AssetJob) -> dict[str, Any]:
        duration = None
        if job.started_at and job.finished_at:
            try:
                duration = max(
                    0.0,
                    (
                        datetime.fromisoformat(job.finished_at)
                        - datetime.fromisoformat(job.started_at)
                    ).total_seconds(),
                )
            except ValueError:
                duration = None
        return {
            "id": job.id,
            "job_family": "asset",
            "job_type": job.job_type,
            "status": job.status,
            "asset_id": job.asset_id,
            "character_id": job.character_id,
            "motion_id": job.motion_id,
            "params": job.params,
            "created_at": job.created_at,
            "updated_at": job.updated_at,
            "started_at": job.started_at,
            "finished_at": job.finished_at,
            "duration_seconds": duration,
            "error": job.error,
        }
